services:
  catalogo:
    build: ./catalogo
    ports:
      - "5001:5000"

  # recomendaciones:
  #   build: ./recomendaciones
  #   ports:
  #     - "5002:5000"

  rankings:
    build: ./rankings
    ports:
      - "5003:5000"
    environment:
      - CATALOGO_URL=http://catalogo:5000
      - CALIFICACIONES_URL=http://calificaciones:5000
      - USAR_CALIFICACIONES_PRUEBA=true
    depends_on:
      - catalogo

  # calificaciones:
  #   build: ./calificaciones
  #   ports:
  #     - "5004:5000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      CALIFICACIONES_URL: http://calificaciones:5004
    depends_on:
      - catalogo