services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: catalogo
      POSTGRES_DB: catalogo
    ports:
      - "5432:5432"

  catalogo:
    build: ./catalogo
    ports:
      - "5001:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: catalogo
      POSTGRES_DB: catalogo
    volumes:
      - ./docs:/app/docs:ro
    depends_on:
      - db

  # recomendaciones:
  #   build: ./recomendaciones
  #   ports:
  #     - "5002:5000"

  rankings:
    build: ./rankings
    ports:
      - "5003:5000"
    environment:
      - CATALOGO_URL=http://catalogo:5000
      - CALIFICACIONES_URL=http://calificaciones:5000
      - USAR_CALIFICACIONES_PRUEBA=true
    depends_on:
      - catalogo

  # calificaciones:
  #   build: ./calificaciones
  #   ports:
  #     - "5004:5000"

  # frontend:
  #   image: nginx:alpine
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html
  #   ports:
  #     - "8080:80"