# Generated by Django 6.1.1 on 2026-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('titulo', 'anio'), name='titulo_anio_unico')],
            },
        ),
    ]
